name: Lyric Bot (Windows Runner)

on:
  # 1) Schedule to run every 3 hours
  schedule:
    - cron: "0 */3 * * *"
  # 2) Allows manual (on-demand) runs
  workflow_dispatch:

jobs:
  run-lyric-bot:
    runs-on: windows-latest
    steps:
      # 3) Check out your repository
      - name: Check out code
        uses: actions/checkout@v3

      # 4) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 5) Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6) Run your script
      - name: Run lyric script
        run: python lyrics_bot.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
