name: Lyric Bot

on:
  schedule:
    # Runs every day at 12:00 (UTC). Adjust as needed.
    - cron: '0 12 * * *'
  # Allows you to run it manually via the Actions tab
  workflow_dispatch:

jobs:
  run-lyric-bot:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install system dependencies (for fonts, etc.)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttf-mscorefonts-installer
          sudo fc-cache -fv

      # 4) Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Run your Python script
      - name: Run lyric script
        run: python lyrics_bot.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
