name: Lyric Bot (Windows Runner with UTF-8)

on:
  schedule:
    # Runs every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-lyric-bot:
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Force UTF-8 in PowerShell
        shell: pwsh
        run: |
          # Change the console codepage to UTF-8
          chcp 65001
          # Set Python to always use UTF-8 for stdin/stdout
          $env:PYTHONIOENCODING = "utf-8"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lyric script
        shell: pwsh
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |
          python lyrics_bot.py
